### ISSUE TITLE
error with new build-docker-images.sh in ash

### ISSUE THREAD

**Issue by missinglink** [pelias/ci-tools#3]
hey @orangejulius, it looks like the `bash` array syntax is not portable to `ash` (alpine linux).

I opened a PR on geonames today which failed:

```
#!/bin/sh -eo pipefail
apk --no-cache add curl && curl "https://raw.githubusercontent.com/pelias/ci-tools/master/build-docker-images.sh" | sh -
```

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/1) Installing curl (7.61.1-r0)
7  0%                                             87100% ############################################8Executing busybox-1.28.4-r1.trigger
OK: 22 MiB in 23 packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100  1142  100  1142    0     0  34606      0 --:--:-- --:--:-- --:--:-- 34606
sh: syntax error: unexpected "("
Exited with code 2
```

The offending line is `21`, which is due to the `bash` array syntax not being supported.

I had a quick look at it but I didn't want to go down a path and then having to revert it, some ideas I had:
- rewrite to use a portable array syntax
- use a different shell in `alpine`
- don't use `alpine` at all

ref: https://unix.stackexchange.com/questions/384614/how-to-port-to-bash-style-arrays-to-ash

**Comment by orangejulius** [comment]
Yeah, I've been fixing this by updating our Circle scripts to install bash in https://github.com/pelias/geonames/pull/343 https://github.com/pelias/schema/pull/332 and https://github.com/pelias/api/pull/1227

**Comment by orangejulius** [comment]
Should be fixed everywhere we already use the ci-tools.
